# Generated by Django 3.2 on 2022-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
