# Generated by Django 3.2 on 2022-04-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(blank=True, default='EUR', max_length=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='currencies.currency'),
        ),
    ]
