# Generated by Django 3.2 on 2022-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
    ]
