# Generated by Django 3.2 on 2022-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.CharField(blank=True, max_length=254, null=True)),
                ('condition', models.CharField(blank=True, max_length=254, null=True)),
                ('fuel', models.CharField(blank=True, max_length=254, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.CharField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('number_of_views_last_7_days', models.IntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, to='products.Category')),
            ],
        ),
    ]
