# Generated by Django 3.2 on 2022-04-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='number_of_views_last_7_days',
            new_name='number_of_views',
        ),
        migrations.AddField(
            model_name='boat',
            name='sku',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
