# Generated by Django 3.2 on 2022-04-13 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220408_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
