# Generated by Django 3.2 on 2022-04-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_boat_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['-image', '-views']},
        ),
        migrations.RenameField(
            model_name='boat',
            old_name='number_of_views',
            new_name='views',
        ),
    ]
