# Generated by Django 3.2 on 2022-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220413_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
