# Generated by Django 3.2 on 2022-04-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('products', '0006_alter_boat_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='currency',
            field=models.ForeignKey(blank=True, default='EUR', max_length=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='currencies.currency'),
        ),
    ]
