# Generated by Django 3.2 on 2022-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_boat_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
