# Generated by Django 3.2 on 2022-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_boat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='sku',
            field=models.CharField(default='test', max_length=10, unique=True),
        ),
    ]
