# Generated by Django 3.2 on 2022-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_boat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
