# Generated by Django 3.2 on 2022-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220425_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='dimensions',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
