# Generated by Django 3.2 on 2022-04-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_boat_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='dimensions',
        ),
    ]
