# Generated by Django 3.2 on 2022-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_boat_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
