# Generated by Django 3.2 on 2022-04-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220428_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='image_url',
        ),
    ]
