# Generated by Django 3.2 on 2022-09-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_boat_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['-views']},
        ),
    ]
